# Generated by Django 4.1 on 2022-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
