# Generated by Django 4.1 on 2022-09-26 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_articlemodel_delete_articlemodle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
