# Generated by Django 4.1 on 2022-10-29 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_categorymodel_articlemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='post.categorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='Image'),
        ),
    ]
