# Generated by Django 4.1 on 2022-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_articlemodel_category_alter_articlemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
