# Generated by Django 4.1 on 2022-09-09 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofilemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801********6'. Up to 11 digits allowed.", regex='^01[3-9]\\d{8}$')]),
        ),
    ]
